name = "dda-portal"
main = ".open-next/worker.js"
compatibility_date = "2026-03-15"
pages_build_output_dir = ".open-next"

# Development / Preview Configuration
[vars]
NEXT_PUBLIC_SITE_URL = "https://dda-portal.pages.dev"

# D1 Database Binding
[[d1_databases]]
binding = "DB" 
database_name = "dda-db"
database_id = "08671e5e-f1c2-4507-bc7d-7335c3b13da7"
migrations_dir = "drizzle"

# KV Namespace for Stories and Sessions
[[kv_namespaces]]
binding = "KV_DATA"
id = "377aaf2e1e2445ae92713c1a26758694" 

[site]
bucket = ".open-next/assets"

[build]
command = "npm run build"
watch_dir = "src"
