name = "dda-portal"
main = ".open-next/worker.js"
compatibility_date = "2026-03-16"
compatibility_flags = ["nodejs_compat_v2"]
pages_build_output_dir = ".open-next"

[site]
bucket = ".open-next/assets"

# D1 Binding
[[d1_databases]]
binding = "DB"
database_name = "dda-db"
database_id = "08671e5e-f1c2-4507-bc7d-7335c3b13da7"
migrations_dir = "drizzle"


[vars]
NEXT_PUBLIC_SITE_URL = "https://dda-portal.pages.dev"



[[kv_namespaces]]
binding = "KV_DATA"
id = "377aaf2e1e2445ae92713c1a26758694"
